version: '3.3'

services:
  api:
    build: .
    command: python /app/api.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/get_data"]
      interval: 15s
      timeout: 5s
      retries: 3

  agent:
    build: .
    command: python /app/agent.py
    volumes:
      - .:/app
    depends_on:
      api:
        condition: service_healthy

